
#---standard pioneer footprint---
#---(in meters)---
#footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
footprint: [ [0.3,0.22], [0.3,-0.22], [-0.3,-0.22], [-0.3,0.22] ]
#footprint: [ [-0.1,-0.125], [0.5,-0.125], [0.5,0.125], [-0.1,0.125] ]

transform_tolerance: 1
map_type: costmap

static_layer:
  enabled:              true
  map_topic:            "/map"


obstacle_layer:
  enabled: true
  obstacle_range: 3.0
  raytrace_range: 3.5 ######if bigger????
  inflation_radius: 0.15
  track_unknown_space: false
  combination_method: 1
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {inf_is_valid: true, sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  
inflation_layer:
  enabled:              true
  cost_scaling_factor:  1.0   # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.25  #  max. distance from an obstacle at which costs are incurred for planning paths.




